### ISSUE TITLE
Release Checklist -- 2017-06-02

### ISSUE THREAD

**Issue by vaxinate** [revelrylabs/adam-test-repo#13]
- [ ] Check this off
- [ ] and this one too
- [ ] what if I add another before pushing?
